"""
Tests for checkpoint._drop_hallucinated_files (2026-08-15) — a real handover
generated by this repo invented two files that never existed
(askr/daemon/quota_monitor.py, askr/daemon/rate_limit_resume.py) in
relational_files. Same class of problem as the next_actions staleness fix
(97c5b19): trusting LLM-generated claims about the codebase without checking
them against ground truth. Deterministic, no LLM call — only ever removes
entries, never edits or invents one.
"""

import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from askr.session import checkpoint


class FileExistsRelativeOrAbsoluteTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.project_path = self._tmp.name
        with open(os.path.join(self.project_path, "real.py"), "w") as f:
            f.write("# real\n")

    def tearDown(self):
        self._tmp.cleanup()

    def test_relative_real_file_exists(self):
        self.assertTrue(checkpoint._file_exists_relative_or_absolute("real.py", self.project_path))

    def test_relative_fake_file_does_not_exist(self):
        self.assertFalse(checkpoint._file_exists_relative_or_absolute("fake.py", self.project_path))

    def test_absolute_real_file_exists(self):
        abs_path = os.path.join(self.project_path, "real.py")
        self.assertTrue(checkpoint._file_exists_relative_or_absolute(abs_path, self.project_path))

    def test_absolute_fake_file_does_not_exist(self):
        self.assertFalse(checkpoint._file_exists_relative_or_absolute("/nonexistent/fake.py", self.project_path))

    def test_empty_string_is_false(self):
        self.assertFalse(checkpoint._file_exists_relative_or_absolute("", self.project_path))

    def test_none_is_false(self):
        self.assertFalse(checkpoint._file_exists_relative_or_absolute(None, self.project_path))

    def test_non_string_is_false(self):
        self.assertFalse(checkpoint._file_exists_relative_or_absolute(123, self.project_path))


class DropHallucinatedFilesTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.project_path = self._tmp.name
        os.makedirs(os.path.join(self.project_path, "askr", "session"))
        with open(os.path.join(self.project_path, "askr", "session", "lifecycle.py"), "w") as f:
            f.write("# real\n")

    def tearDown(self):
        self._tmp.cleanup()

    def test_real_file_in_play_survives(self):
        summary = {"files_in_play": ["askr/session/lifecycle.py"]}
        result = checkpoint._drop_hallucinated_files(summary, self.project_path)
        self.assertEqual(result["files_in_play"], ["askr/session/lifecycle.py"])

    def test_fabricated_file_in_play_is_dropped(self):
        summary = {"files_in_play": ["askr/daemon/quota_monitor.py"]}
        result = checkpoint._drop_hallucinated_files(summary, self.project_path)
        self.assertEqual(result["files_in_play"], [])

    def test_mixed_files_in_play_only_real_ones_survive(self):
        summary = {"files_in_play": ["askr/session/lifecycle.py", "askr/daemon/quota_monitor.py"]}
        result = checkpoint._drop_hallucinated_files(summary, self.project_path)
        self.assertEqual(result["files_in_play"], ["askr/session/lifecycle.py"])

    def test_real_relational_file_survives(self):
        summary = {"relational_files": [{"file": "askr/session/lifecycle.py", "relationship": "imports"}]}
        result = checkpoint._drop_hallucinated_files(summary, self.project_path)
        self.assertEqual(len(result["relational_files"]), 1)

    def test_fabricated_relational_file_is_dropped(self):
        # The exact real-world case: askr/daemon/ never existed as a module.
        summary = {"relational_files": [
            {"file": "askr/daemon/quota_monitor.py", "relationship": "imports"},
            {"file": "askr/daemon/rate_limit_resume.py", "relationship": "imported_by"},
        ]}
        result = checkpoint._drop_hallucinated_files(summary, self.project_path)
        self.assertEqual(result["relational_files"], [])

    def test_relational_file_entry_missing_file_key_is_dropped(self):
        summary = {"relational_files": [{"relationship": "imports"}]}
        result = checkpoint._drop_hallucinated_files(summary, self.project_path)
        self.assertEqual(result["relational_files"], [])

    def test_relational_file_non_dict_entry_is_dropped(self):
        summary = {"relational_files": ["askr/session/lifecycle.py"]}
        result = checkpoint._drop_hallucinated_files(summary, self.project_path)
        self.assertEqual(result["relational_files"], [])

    def test_missing_fields_are_noop(self):
        summary = {"task": "did stuff"}
        result = checkpoint._drop_hallucinated_files(summary, self.project_path)
        self.assertEqual(result, {"task": "did stuff"})

    def test_non_dict_summary_passed_through_untouched(self):
        # Legacy string-form handover from a degraded fallback — must not raise.
        result = checkpoint._drop_hallucinated_files("plain text handover", self.project_path)
        self.assertEqual(result, "plain text handover")

    def test_none_summary_passed_through_untouched(self):
        try:
            result = checkpoint._drop_hallucinated_files(None, self.project_path)
        except Exception as e:
            self.fail(f"_drop_hallucinated_files raised: {e}")
        self.assertIsNone(result)

    def test_non_list_files_in_play_left_untouched(self):
        # Malformed LLM output (a string instead of a list) — must not crash,
        # must not silently coerce into something wrong.
        summary = {"files_in_play": "not-a-list"}
        try:
            result = checkpoint._drop_hallucinated_files(summary, self.project_path)
        except Exception as e:
            self.fail(f"_drop_hallucinated_files raised: {e}")
        self.assertEqual(result["files_in_play"], "not-a-list")

    def test_other_summary_fields_untouched(self):
        summary = {
            "task": "did stuff",
            "files_in_play": ["askr/daemon/quota_monitor.py"],
            "decisions": ["some decision"],
        }
        result = checkpoint._drop_hallucinated_files(summary, self.project_path)
        self.assertEqual(result["task"], "did stuff")
        self.assertEqual(result["decisions"], ["some decision"])
        self.assertEqual(result["files_in_play"], [])


if __name__ == "__main__":
    unittest.main()
